title: 水滸傳 - 吳淡如
description: 水滸傳 - 吳淡如
time: Mon, 26 Aug 2024 04:23:37 +0000
items:
  - title: 00. 自序─當皇上昏庸，忠誠只是一場荒唐夢
    size: 5089280
    duration: 423
  - title: 01. 壹─糊塗太尉放了魔星
    size: 4948516
    duration: 412
  - title: 02. 貳─禁軍教頭走投無路
    size: 16580633
    duration: 1036
  - title: 03. 參─花和尚大鬧五臺山
    size: 13099033
    duration: 818
  - title: 04. 肆─豹子頭林冲何去何從
    size: 21487475
    duration: 1342
  - title: 05. 伍─世家公子柴進英雄惜英雄
    size: 12684005
    duration: 792
  - title: 06. 陸─這一票非幹不可
    size: 13120764
    duration: 819
  - title: 07. 柒─沒有人立志當山賊，但是......
    size: 14034861
    duration: 877
  - title: 08. 捌─武松打虎
    size: 16900781
    duration: 1056
  - title: 09. 玖─潘金蓮的悲劇
    size: 16436015
    duration: 1027
  - title: 10. 拾─人肉包子店
    size: 14723216
    duration: 920
  - title: 11. 拾壹─誰都怕黑旋風李逵
    size: 19419413
    duration: 1213
  - title: 12. 拾貳─梁山泊好漢救宋江
    size: 14044458
    duration: 877
  - title: 13. 拾參─兄弟當然比老婆重要
    size: 14634619
    duration: 914
  - title: 14. 拾肆─先打下高唐州再說！
    size: 13534132
    duration: 845
  - title: 15. 拾伍─北京貴公子也變綠林好漢
    size: 17922708
    duration: 1120
  - title: 16. 拾陸─一零八好漢齊聚梁山泊
    size: 15182147
    duration: 948
  - title: 17. 拾柒─宋江的招安大夢
    size: 15619744
    duration: 976
  - title: 18. 拾捌─陌路英雄的悲歌
    size: 13392440
    duration: 836
